http:
  routers:
    composer:
      rule: Host(`composer.flashsale`)
      entryPoints:
        - web
      service: composer-svc

    auth:
      rule: Host(`auth.flashsale`)
      entryPoints:
        - web
      priority: 10
      service: auth-svc

    auth-ui:
      rule: Host(`auth.flashsale`) && (PathPrefix(`/templates`) || PathPrefix(`/static`))
      entryPoints:
        - web
      priority: 20
      service: auth-ui-svc

    inventory:
      rule: Host(`inventory.flashsale`)
      entryPoints:
        - web
      service: inventory-svc

    payment:
      rule: Host(`payment.flashsale`)
      entryPoints:
        - web
      service: payment-svc

    traefik-dashboard:
      rule: Host(`traefik.flashsale`)
      entryPoints:
        - web
      service: api@internal

    grafana:
      rule: Host(`grafana.flashsale`)
      entryPoints:
        - web
      service: grafana-svc

    vault:
      rule: Host(`vault.flashsale`)
      entryPoints:
        - web
      service: vault-svc

    jaeger:
      rule: Host(`jaeger.flashsale`)
      entryPoints:
        - web
      service: jaeger-svc

  services:
    composer-svc:
      loadBalancer:
        servers:
          - url: http://composer:8000

    auth-svc:
      loadBalancer:
        servers:
          - url: http://auth-service:8000

    auth-ui-svc:
      loadBalancer:
        servers:
          - url: http://auth-frontend:80

    inventory-svc:
      loadBalancer:
        servers:
          - url: http://inventory-service:8000

    payment-svc:
      loadBalancer:
        servers:
          - url: http://payment-service:8000

    grafana-svc:
      loadBalancer:
        servers:
          - url: http://grafana:3000

    vault-svc:
      loadBalancer:
        servers:
          - url: http://vault:8200

    jaeger-svc:
      loadBalancer:
        servers:
          - url: http://jaeger:16686
